begin;
do $$
declare tid uuid:=gen_random_uuid(); code text:=gen_random_uuid()::text; t public.tickets%rowtype; first_end timestamptz; blocked boolean; sid uuid;
begin
 update public.app_settings set value='qa-variance-supervisor' where key='supervisor_username';
 update public.app_settings set value=extensions.crypt(code,extensions.gen_salt('bf')) where key='supervisor_code';
 update public.app_settings set value='qa-variance-operator' where key='operator_username';
 update public.app_settings set value=extensions.crypt(code,extensions.gen_salt('bf')) where key='operator_code';
 sid:=public.add_staff_with_photo_as_supervisor('qa-variance-supervisor',code,'QA-VARIANCE-STAFF',null);
 insert into public.tickets(id,ticket_no,job_type_id,assignee_id,status,started_at,materials) values(tid,'QA-VARIANCE-'||tid,(select id from public.job_types where active limit 1),sid,'active',now()-interval '10 minutes','[{"pk_code":"QA","pk_name":"QA","unit":"ชิ้น","required_qty":10}]');
 select * into t from public.tickets where id=tid;
 blocked:=false;
 begin perform public.confirm_ticket_picks_as_operator('qa-variance-operator',code,tid,t.materials,t.status,'[{"actual_qty":12}]','done'); exception when others then if sqlerrm like 'กรุณาระบุเหตุผล%' then blocked:=true; else raise; end if; end;
 if not blocked then raise exception 'FAIL excess reason'; end if;
 perform public.confirm_ticket_picks_as_operator('qa-variance-operator',code,tid,t.materials,t.status,'[{"actual_qty":12,"short_reason":"เบิกเผื่อ"}]','done');
 select * into t from public.tickets where id=tid;first_end:=t.ended_at;
 if t.status<>'done' or (t.materials->0->>'actual_qty')::numeric<>12 or t.materials->0->>'short_reason'<>'เบิกเผื่อ' then raise exception 'FAIL excess done'; end if;
 blocked:=false;
 begin perform public.edit_ticket_picks_as_supervisor('qa-variance-operator',code,tid,t.materials,t.status,'[{"actual_qty":8,"short_reason":"ขาด"}]','แก้'); exception when others then if sqlerrm='Supervisor access required' then blocked:=true; else raise; end if; end;
 if not blocked then raise exception 'FAIL supervisor auth'; end if;
 blocked:=false;
 begin perform public.edit_ticket_picks_as_supervisor('qa-variance-supervisor',code,tid,t.materials,t.status,'[{"actual_qty":8,"short_reason":"ขาด"}]',' '); exception when others then if sqlerrm like 'กรุณาระบุเหตุผล%' then blocked:=true; else raise; end if; end;
 if not blocked then raise exception 'FAIL edit reason'; end if;
 perform public.edit_ticket_picks_as_supervisor('qa-variance-supervisor',code,tid,t.materials,t.status,'[{"actual_qty":8,"short_reason":"ขาด 2"}]','ปรับข้อมูล');
 select * into t from public.tickets where id=tid;
 if t.status<>'partial' or t.ended_at is distinct from first_end then raise exception 'FAIL partial and time'; end if;
 blocked:=false;
 begin perform public.edit_ticket_picks_as_supervisor('qa-variance-supervisor',code,tid,'[]',t.status,'[{"actual_qty":10}]','ข้อมูลเก่า'); exception when others then if sqlerrm like 'ใบเบิกถูกแก้ไข%' then blocked:=true; else raise; end if; end;
 if not blocked then raise exception 'FAIL concurrency'; end if;
 perform public.edit_ticket_picks_as_supervisor('qa-variance-supervisor',code,tid,t.materials,t.status,'[{"actual_qty":10}]','แก้ยอดครบ');
 select * into t from public.tickets where id=tid;
 if t.status<>'done' or t.ended_at is distinct from first_end then raise exception 'FAIL done and time'; end if;
 if (select count(*) from public.ticket_events where ticket_id=tid and actor_role='supervisor' and event_type='edited')<>2 then raise exception 'FAIL edit audit'; end if;
 blocked:=false;
 begin perform public.rename_staff_as_supervisor('qa-variance-operator',code,sid,'new'); exception when others then if sqlerrm='Supervisor access required' then blocked:=true; else raise; end if; end;
 if not blocked then raise exception 'FAIL rename auth'; end if;
 perform public.rename_staff_as_supervisor('qa-variance-supervisor',code,sid,'QA-VARIANCE-RENAMED');
 if not exists(select 1 from public.staff where id=sid and display_name='QA-VARIANCE-RENAMED') then raise exception 'FAIL rename'; end if;
end $$;
rollback;
