import {defaultSettings,settingsError,varianceRows,matchesText,safeCsv,planOrder} from './management.mjs?v=2';
import {configureWorkTime,workBreakdown,minutesText,operationalPerformance,pickCompleteness,reasonLabels} from './operations.mjs';
import {totalDocuments,ticketDocumentCount} from './withdrawal-documents.mjs';
import {fromBangkokInput,toBangkokInput,formatBangkokDateTime} from './ticket-time.mjs?v=2';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date(Date.now()+7*3600000).toISOString().slice(0,10);
const number=v=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:4}).format(v);
const statusText={open:'รอติดตาม',following:'กำลังติดตาม',resolved:'จัดการแล้ว'};
const priorities={normal:'ปกติ',high:'สำคัญ',urgent:'ด่วน'};
const heading=(title,description)=>`<div class="section-heading"><div><h2>${title}</h2><p class="hint">${description}</p></div></div>`;
const field=(title,html)=>`<label>${title}${html}</label>`;
const table=(headers,rows)=>`<div class="management-table-wrap"><table class="management-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}">ไม่มีข้อมูลตามตัวกรอง</td></tr>`}</tbody></table></div>`;

export function installManagement(ctx){
 const {state,supervisor,editing,showView,notice,load,nameFor,jobFor}=ctx;
 state.management={settings:{...defaultSettings},cases:[]};state.managementReady=false;
 let history=[],historyLoading=false,historyLoaded=false,planTicket=null,caseRow=null,settingsSnapshot=null;
 const clerk=()=>editing()&&state.role==='clerk',canCases=()=>supervisor()||clerk();
 const rpc=(action,args)=>state.db.rpc('manage_work',{p_username:state.username,p_code:state.code,p_role:state.role,p_action:action,p_args:args});
 const nav=$('#nav');
 nav.querySelector('[data-view=tickets]').insertAdjacentHTML('afterend',`<button data-view="planning"><span>▦</span> แผนงานประจำวัน</button><button data-view="exceptions"><span>!</span> ของขาด / เบิกเกิน</button><button data-view="analytics"><span>▥</span> รายงานและวิเคราะห์</button><button data-view="audit" class="management-private" hidden><span>↺</span> ประวัติรวม</button>`);
 nav.insertAdjacentHTML('beforeend','<button data-view="system" class="admin-only" hidden><span>⚙</span> ตั้งค่าระบบ</button>');
 $('#role-select').insertAdjacentHTML('beforeend','<option value="clerk">ธุรการ · ติดตามของขาด–เบิกเกิน</option>');
 const main=$('main');
 main.insertAdjacentHTML('beforeend',`
 <section id="planning-view" class="view" hidden>${heading('แผนงานประจำวัน','จัดลำดับงานและมอบหมายให้ทีม · หัวหน้าแก้แผนได้ · งานที่จบแล้วดูในรายงาน')}<div class="management-filters">${field('วันที่วางแผน','<input id="plan-date" type="date" value="'+today()+'">')}${field('แสดงงาน','<select id="plan-scope"><option value="day">ตามวันที่</option><option value="unplanned">ยังไม่วางแผน</option><option value="overdue">เลยกำหนดส่ง</option><option value="all">งานที่ยังเปิดทั้งหมด</option></select>')}${field('พนักงาน','<select id="plan-person"><option value="">ทุกคน</option></select>')}</div><p id="plan-summary" class="hint"></p><div id="plan-list" class="management-grid"></div></section>
 <section id="exceptions-view" class="view" hidden>${heading('ติดตามของขาด / เบิกเกิน','จัดการครบทุกเรื่องแล้ว ใบที่ปิดงานจะแสดงเบิกครบ · เก็บยอดเบิกเดิมเป็นประวัติ')}<p id="exception-owner" class="management-banner"></p><div class="management-filters">${field('ค้นหา','<input id="case-search" type="search" placeholder="เลขใบเบิก รหัส ชื่อวัสดุ หรือพนักงาน">')}${field('ประเภท','<select id="case-type"><option value="">ทั้งหมด</option><option value="short">ของขาด</option><option value="over">เบิกเกิน</option></select>')}${field('สถานะติดตาม','<select id="case-status"><option value="pending">เรื่องที่ยังไม่ปิด</option><option value="all">ทั้งหมด</option><option value="open">รอติดตาม</option><option value="following">กำลังติดตาม</option><option value="resolved">จัดการแล้ว</option></select>')}</div><p id="case-count" class="hint"></p><div id="case-list" class="management-grid"></div></section>
 <section id="analytics-view" class="view" hidden>${heading('รายงานและวิเคราะห์','งานจบตามวันที่สิ้นสุด · แยกใบ งาน และรายการวัสดุ · เทียบความเร็วเฉพาะงานข้อมูลครบที่มีมาตรฐานตรงกัน')}<div class="management-filters">${field('ตั้งแต่วันที่','<input id="analytics-from" type="date">')}${field('ถึงวันที่','<input id="analytics-to" type="date">')}${field('พนักงาน','<select id="analytics-person"><option value="">ทุกคน</option></select>')}${field('ประเภทงาน','<select id="analytics-job"><option value="">ทุกประเภทงาน</option></select>')}${field('สรุปตาม','<select id="analytics-group"><option value="person">พนักงาน</option><option value="job">ประเภทงาน</option><option value="day">รายวัน</option><option value="month">รายเดือน</option></select>')}</div><div class="management-actions"><span id="analytics-summary" class="hint"></span><button id="analytics-csv" class="text-btn">ส่งออก Excel (CSV)</button><button id="analytics-print" class="primary">พิมพ์ / PDF</button></div><div id="analytics-table"></div></section>
 <section id="audit-view" class="view" hidden>${heading('ประวัติการทำรายการรวม','ตรวจการสร้าง แก้ไข เริ่ม–จบ ติดตาม และตั้งค่า · การลบถาวรเก็บเฉพาะเลขใบ ผู้ลบ เวลา และเหตุผล')}<div class="management-filters">${field('ค้นหา','<input id="audit-search" type="search" placeholder="เลขใบ ผู้ทำรายการ หรือเหตุผล">')}${field('ตั้งแต่วันที่','<input id="audit-from" type="date">')}${field('ถึงวันที่','<input id="audit-to" type="date">')}<button id="audit-reload" class="text-btn">โหลดประวัติใหม่</button></div><p id="audit-count" class="hint"></p><div id="audit-list"></div><button id="audit-more" class="text-btn" hidden>แสดงเพิ่มเติม</button></section>
 <section id="system-view" class="view" hidden>${heading('ตั้งค่าระบบ','เวลาไทย · การเปลี่ยนกะหรือวันหยุดจะคำนวณเวลาสุทธิของทุกงานใหม่ รวมงานย้อนหลัง')}<form id="system-form" class="management-form">${field('เริ่มกะ','<input name="start" type="time" required>')}${field('สิ้นสุดกะ','<input name="end" type="time" required>')}${field('เริ่มพักเที่ยง','<input name="lunchStart" type="time" required>')}${field('สิ้นสุดพักเที่ยง','<input name="lunchEnd" type="time" required>')}${field('ผู้รับผิดชอบของขาด–เบิกเกิน','<select name="exceptionOwnerId" required></select>')}${field('วันหยุดที่ไม่นับเวลาทำงาน','<textarea name="holidays" placeholder="YYYY-MM-DD หนึ่งวันต่อบรรทัด"></textarea>')}<div id="reason-fields" class="management-reason-fields"></div><p class="hint">วันอื่นนับตามกะ รวมเสาร์–อาทิตย์ หากหยุดให้เพิ่มวันที่ในรายการ · ประเภทเหตุผลมาตรฐานใช้ร่วมกับข้อมูลเดิมเพื่อให้รายงานเปรียบเทียบได้</p><button class="primary">บันทึกตั้งค่า</button><button type="button" id="system-reset" class="text-btn">โหลดค่าล่าสุด / ล้างการแก้ไข</button><p id="system-message" role="status"></p></form><h3>ประเภทเหตุผลของขาด–เบิกเกิน</h3><div id="reason-categories" class="management-banner"></div><h3>บัญชีธุรการ</h3><p class="hint">สิทธิ์ดูประวัติและติดตามเรื่องขาด–เกิน ไม่มีสิทธิ์แก้ใบเบิกหรือยอดเบิกจริง</p><form id="clerk-account-form" class="management-form">${field('ชื่อผู้ใช้','<input name="username" required maxlength="80" autocomplete="off">')}${field('รหัสผ่านใหม่','<input name="password" type="password" required minlength="6" maxlength="128" autocomplete="new-password">')}<button class="primary">บันทึกบัญชีธุรการ</button><p id="clerk-account-message" role="status"></p></form><p><button id="system-standards" class="text-btn">จัดการประเภทงาน ทักษะ และเวลามาตรฐาน →</button></p></section>`);
 document.body.insertAdjacentHTML('beforeend',`
 <dialog id="plan-dialog"><form id="plan-form" class="dialog-content"><div class="dialog-head"><h2>ปรับแผนงาน</h2><button type="button" data-close class="icon-btn" aria-label="ปิด">×</button></div><p id="plan-title"></p>${field('วันวางแผน','<input name="planned_date" type="date">')}${field('กำหนดส่ง (เวลาไทย)','<input name="due_at" type="datetime-local">')}${field('มอบหมายให้','<select name="assignee_id" required></select>')}${field('ความเร่งด่วน','<select name="priority"><option value="normal">ปกติ</option><option value="high">สำคัญ</option><option value="urgent">ด่วน</option></select>')}<p id="plan-message" role="status"></p><div class="dialog-actions"><button type="button" data-close class="text-btn">ยกเลิก</button><button class="primary">บันทึกแผน</button></div></form></dialog>
 <dialog id="case-dialog"><form id="case-form" class="dialog-content"><div class="dialog-head"><h2>บันทึกผลติดตาม</h2><button type="button" data-close class="icon-btn" aria-label="ปิด">×</button></div><p id="case-title"></p><p class="hint">เมื่อทุกเรื่องของใบที่ปิดงานถูกจัดการแล้ว ใบเบิกจะแสดงเบิกครบ โดยเก็บยอดเบิกเดิมไว้ หากแก้ยอดหรือเปิดเรื่องใหม่จะกลับมาติดตามอีกครั้ง</p>${field('สถานะติดตาม','<select name="status"><option value="open">รอติดตาม</option><option value="following">กำลังติดตาม</option><option value="resolved">จัดการแล้ว</option></select>')}${field('รายละเอียด / ผลดำเนินการ','<textarea name="note" required maxlength="1000" placeholder="ประสานใคร ได้ข้อสรุปอย่างไร"></textarea>')}<p id="case-message" role="status"></p><div class="dialog-actions"><button type="button" data-close class="text-btn">ยกเลิก</button><button class="primary">บันทึกผลติดตาม</button></div></form></dialog>`);
 const fillPeople=el=>{const v=el.value;el.innerHTML=(el.id?' <option value="">ทุกคน</option>':'')+state.people.filter(p=>p.active).map(p=>`<option value="${esc(p.id)}">${esc(p.display_name)}</option>`).join('');el.value=v;};
 function modes(){document.querySelectorAll('.management-private').forEach(el=>el.hidden=!canCases());if(!canCases()&&state.view==='audit')showView('dashboard');if(!supervisor()&&state.view==='system')showView('dashboard');if(clerk())$('#user-label').textContent='ธุรการ · '+state.management.settings.exceptionOwnerName;}
 async function refresh(){
  const {data,error}=await state.db.rpc('get_management_state');
  if(error){state.managementReady=false;notice('โหลดแผนและข้อมูลติดตามไม่สำเร็จ: '+error.message,true);return;}
  state.management={settings:{...defaultSettings,...data.settings},cases:data.cases||[]};state.managementReady=true;configureWorkTime(state.management.settings);
 }
 function renderPlan(){
  const f=$('#plan-person'),old=f.value;fillPeople(f);f.value=old;
  const scope=$('#plan-scope').value,date=$('#plan-date').value;
  const list=planOrder(state.tickets.filter(t=>['queued','active','paused'].includes(t.status)&&(!f.value||t.assignee_id===f.value)&&(scope==='all'||scope==='unplanned'&&!t.planned_date||scope==='overdue'&&t.due_at&&Date.parse(t.due_at)<Date.now()||scope==='day'&&t.planned_date===date)));
  $('#plan-summary').textContent=`${list.length} งาน · ${totalDocuments(list)} ใบ · ${list.reduce((s,t)=>s+(t.materials?.length||0),0)} รายการวัสดุ`;
  $('#plan-list').innerHTML=list.map(t=>`<article class="management-card"><div class="management-card-head"><strong>${esc(t.ticket_no)}</strong><span class="management-badge priority-${t.priority}">${priorities[t.priority||'normal']}</span></div><p>${esc(jobFor(t.job_type_id))} · ${esc(nameFor(t.assignee_id))}</p><p class="hint">${ticketDocumentCount(t)} ใบ · ${t.materials?.length||0} รายการ · วันวางแผน ${esc(t.planned_date||'ยังไม่กำหนด')}</p><p class="${t.due_at&&Date.parse(t.due_at)<Date.now()?'case-short':''}">กำหนดส่ง ${t.due_at?esc(formatBangkokDateTime(t.due_at)):'ยังไม่กำหนด'}</p><div class="management-actions"><button class="text-btn" data-management-ticket="${esc(t.id)}">เปิดใบเบิก</button>${supervisor()?`<button class="primary" data-plan-id="${esc(t.id)}">ปรับแผน / มอบหมาย</button>`:''}</div></article>`).join('')||'<p class="empty">ไม่มีงานในช่วงนี้ เลือก “ยังไม่วางแผน” เพื่อเริ่มจัดคิว</p>';
 }
 function renderCases(){
  const s=state.management.settings;$('#exception-owner').textContent='ผู้รับผิดชอบ: ธุรการ · '+s.exceptionOwnerName+(canCases()?' · คุณบันทึกผลติดตามได้':' · เข้าสู่โหมดธุรการหรือหัวหน้าเพื่อบันทึกผล');
  const all=varianceRows(state.tickets,state.management.cases),type=$('#case-type').value,status=$('#case-status').value;
  const rows=all.filter(r=>(!type||(type==='short'?r.delta<0:r.delta>0))&&(status==='all'||status==='pending'&&r.status!=='resolved'||status===r.status)&&matchesText([r.ticket.ticket_no,r.line.pk_code,r.line.pk_name,nameFor(r.ticket.assignee_id)],$('#case-search').value));
  $('#case-count').textContent=`${rows.length} รายการตามตัวกรอง · ทั้งหมด: ของขาด ${all.filter(r=>r.delta<0).length} · เบิกเกิน ${all.filter(r=>r.delta>0).length} · ยังไม่ปิด ${all.filter(r=>r.status!=='resolved').length}`;
  $('#case-list').innerHTML=rows.map(r=>`<article class="management-card case-${r.delta<0?'short':'over'}"><div class="management-card-head"><strong>${r.delta<0?'▼ ของขาด':'▲ เบิกเกิน'} ${number(Math.abs(r.delta))} ${esc(r.line.unit)}</strong><span class="management-badge">${statusText[r.status]}</span></div><h3>${esc(r.line.pk_code)}</h3><p>${esc(r.line.pk_name)}</p><p>ต้องเบิก ${number(r.line.required_qty)} · เบิกจริง ${number(r.line.actual_qty)} ${esc(r.line.unit)}</p><p class="hint">${esc(r.ticket.ticket_no)} · ${esc(nameFor(r.ticket.assignee_id))}<br>เหตุผล: ${esc(reasonLabels[r.line.reason_code]||'ยังไม่ระบุ')} · ${esc(r.line.short_reason||'—')}</p>${r.stale?'<p class="case-short">ยอดเบิกเปลี่ยนหลังติดตามครั้งก่อน ต้องตรวจใหม่</p>':''}${r.case?`<p class="management-note">${esc(r.case.note)}<br><small>${esc(r.case.updated_by)} · ${esc(formatBangkokDateTime(r.case.updated_at))}</small></p>`:''}<div class="management-actions"><button class="text-btn" data-management-ticket="${esc(r.ticket.id)}">เปิดใบเบิก</button>${canCases()?`<button class="primary" data-case-id="${esc(r.ticket.id)}" data-case-index="${r.index}">บันทึกผลติดตาม</button>`:''}</div></article>`).join('')||'<p class="empty">ไม่มีรายการขาด–เกินตามตัวกรอง</p>';
 }
 function analyticsRows(){
  const from=$('#analytics-from').value,to=$('#analytics-to').value,person=$('#analytics-person').value,job=$('#analytics-job').value,group=$('#analytics-group').value;
  if(from&&to&&from>to){$('#analytics-summary').textContent='วันที่เริ่มต้องไม่หลังวันที่สิ้นสุด';return [];}
  const tickets=state.tickets.filter(t=>['done','partial'].includes(t.status)&&t.ended_at&&(!person||t.assignee_id===person)&&(!job||t.job_type_id===job)&&(!from||toBangkokInput(t.ended_at).slice(0,10)>=from)&&(!to||toBangkokInput(t.ended_at).slice(0,10)<=to));
  const groups=new Map();for(const t of tickets){const key=group==='person'?t.assignee_id:group==='job'?t.job_type_id:toBangkokInput(t.ended_at).slice(0,group==='day'?10:7);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(t);}
  $('#analytics-summary').textContent=`${tickets.length} งานที่จบ · ${totalDocuments(tickets)} ใบ · ตามวันที่จบงาน`;
  return [...groups].sort((a,b)=>a[0].localeCompare(b[0],'th')).map(([key,ts])=>{const q=operationalPerformance(ts,state.standards);return [group==='person'?nameFor(key):group==='job'?jobFor(key):key,ts.length,totalDocuments(ts),ts.reduce((s,t)=>s+(t.materials?.length||0),0),ts.filter(t=>t.status==='done').length,ts.filter(t=>t.status==='partial').length,ts.filter(t=>pickCompleteness(t).complete).length,minutesText(ts.reduce((s,t)=>s+(workBreakdown(t)?.activeMinutes||0),0)),q.efficiency===null?'ไม่มีมาตรฐาน/ข้อมูลไม่ครบ':q.efficiency+'% ('+q.matched+' งาน)'];});
 }
 const reportHeaders=['กลุ่ม','งานที่จบ','จำนวนใบ','รายการวัสดุ','เสร็จแล้ว','เบิกไม่ครบ','ข้อมูลเบิกจริงครบ','เวลาสุทธิรวม','เทียบมาตรฐาน'];
 function renderAnalytics(){for(const id of ['analytics-person'])fillPeople($('#'+id));const f=$('#analytics-job'),v=f.value;f.innerHTML='<option value="">ทุกประเภทงาน</option>'+state.jobs.map(j=>`<option value="${esc(j.id)}">${esc(j.name)}</option>`).join('');f.value=v;$('#analytics-table').innerHTML=table(reportHeaders,analyticsRows().map(row=>'<tr>'+row.map(x=>`<td>${esc(x)}</td>`).join('')+'</tr>').join(''));}
 let auditLimit=50;
 const auditLabels={created:'สร้างใบเบิก',imported:'นำเข้า',started:'เริ่มงาน',paused:'พักงาน',resumed:'ทำงานต่อ',completed:'จบงาน',partial:'เบิกไม่ครบ',cancelled:'ยกเลิก',edited:'แก้ไข / แผนงาน',deleted:'ย้ายถังขยะ',restored:'กู้คืน',purged:'ลบถาวร',case:'ติดตามขาด–เกิน',settings:'แก้ตั้งค่าระบบ',clerk_account:'ตั้งบัญชีธุรการ',staff_added:'เพิ่มพนักงาน',staff_edited:'แก้ไขข้อมูลพนักงาน'};
 function changes(e){
  const a=e.before_state||{},b=e.after_state||{},labels={display_name:'ชื่อพนักงาน',position:'ตำแหน่ง',ticket_no:'เลขที่ใบเบิก',assignee_id:'พนักงาน',job_type_id:'ประเภทงาน',status:'สถานะ',started_at:'เริ่มงาน',ended_at:'จบงาน',planned_date:'วันวางแผน',due_at:'กำหนดส่ง',priority:'ความเร่งด่วน',requested_qty:'จำนวนผลิต',fg_code:'รหัสสินค้า',fg_name:'ชื่อสินค้า',note:'ผลติดตาม',start:'เริ่มกะ',end:'จบกะ',lunchStart:'เริ่มพัก',lunchEnd:'จบพัก',holidays:'วันหยุด',exceptionOwnerName:'ผู้รับผิดชอบ',username:'ชื่อผู้ใช้',status_reason:'เหตุผลสถานะ',deleted_at:'เวลาย้ายถังขยะ'};
  const value=(k,v)=>v===null||v===undefined?'—':k==='assignee_id'?nameFor(v):k==='job_type_id'?jobFor(v):k==='status'?(statusText[v]||{queued:'รอดำเนินการ',active:'กำลังทำ',paused:'พักงาน',done:'เสร็จแล้ว',partial:'เบิกไม่ครบ',cancelled:'ยกเลิก'}[v]||v):k==='priority'?priorities[v]:k.endsWith('_at')?formatBangkokDateTime(v):Array.isArray(v)?v.join(', '):String(v);
  const lines=Object.keys(labels).filter(k=>JSON.stringify(a[k])!==JSON.stringify(b[k])).map(k=>`${labels[k]}: ${value(k,a[k])} → ${value(k,b[k])}`);
  if(JSON.stringify(a.materials)!==JSON.stringify(b.materials)){
   for(const l of b.materials||[]){const old=(a.materials||[]).find(x=>x.pk_code===l.pk_code);if(!old||old.required_qty!==l.required_qty||old.actual_qty!==l.actual_qty||old.short_reason!==l.short_reason)lines.push(`${l.pk_code} · ${l.pk_name||''}: ต้องเบิก ${old?.required_qty??'—'} → ${l.required_qty??'—'} · เบิกจริง ${old?.actual_qty??'—'} → ${l.actual_qty??'—'} ${l.unit||''}${l.short_reason?' · '+l.short_reason:''}`);}
   for(const l of a.materials||[])if(!(b.materials||[]).some(x=>x.pk_code===l.pk_code))lines.push(`นำรายการออก: ${l.pk_code} · ${l.pk_name||''}`);
  }
  return lines.join('\n')||'ไม่มีค่าก่อน–หลังที่บันทึก';
 }
 function renderAudit(){if(!canCases())return;const from=$('#audit-from').value,to=$('#audit-to').value;
  const rows=history.filter(e=>matchesText([e.ticket_no,e.actor_username,e.reason,auditLabels[e.event_type]],$('#audit-search').value)&&(!from||toBangkokInput(e.created_at).slice(0,10)>=from)&&(!to||toBangkokInput(e.created_at).slice(0,10)<=to));
  $('#audit-count').textContent=historyLoading?'กำลังโหลด…':`${rows.length} เหตุการณ์ · แสดง ${Math.min(auditLimit,rows.length)}`;
  $('#audit-list').innerHTML=rows.slice(0,auditLimit).map(e=>`<article class="management-card audit-card"><div class="management-card-head"><strong>${esc(auditLabels[e.event_type]||e.event_type)} · ${esc(e.ticket_no||'ระบบ')}</strong><time>${esc(formatBangkokDateTime(e.created_at))}</time></div><p class="hint">${esc(e.actor_username)} · ${e.actor_role==='clerk'?'ธุรการ':e.actor_role==='supervisor'?'หัวหน้า':'ผู้ปฏิบัติงาน'}${e.reason?' · '+esc(e.reason):''}</p>${e.event_type!=='purged'?`<details><summary>ดูค่าก่อน–หลัง</summary><pre>${esc(changes(e))}</pre></details>`:'<p class="hint">เก็บเฉพาะหลักฐานการลบ ไม่มีข้อมูลวัสดุหรือรูปพนักงาน</p>'}</article>`).join('')||'<p class="empty">ไม่มีประวัติตามตัวกรอง</p>';$('#audit-more').hidden=rows.length<=auditLimit;
 }
 async function fetchHistory(){if(!canCases()||historyLoading)return;historyLoading=true;renderAudit();const {data,error}=await rpc('history',{});historyLoading=false;if(error){notice('โหลดประวัติไม่สำเร็จ: '+error.message,true);return;}history=data||[];historyLoaded=true;renderAudit();}
 function renderSystem(force=false){const f=$('#system-form');if(force||!f.contains(document.activeElement)&&!f.dataset.dirty){const s=state.management.settings;$('#reason-fields').innerHTML=Object.entries(reasonLabels).map(([key,label])=>field('ชื่อเหตุผล: '+label,`<input data-reason-name="${key}" value="${esc(label)}" required maxlength="80">`)).join('');settingsSnapshot=structuredClone(s);for(const k of ['start','end','lunchStart','lunchEnd'])f.elements[k].value=s[k];fillPeople(f.elements.exceptionOwnerId);f.elements.exceptionOwnerId.value=s.exceptionOwnerId||'';f.elements.holidays.value=s.holidays.join('\n');}$('#reason-categories').textContent=Object.values(reasonLabels).join(' · ');}
 function render(){modes();renderPlan();renderCases();renderAnalytics();if(canCases()&&state.view==='audit'&&!historyLoaded)fetchHistory();if(supervisor())renderSystem();const s=state.management.settings;$('.operations-heading p').textContent=`กะ ${s.start}–${s.end} · พัก ${s.lunchStart}–${s.lunchEnd} · เวลาไทย · วันหยุด ${s.holidays.length} วัน`;}
 async function save(form,action,args,target,success){if(!state.managementReady){$(target).textContent='ข้อมูลยังไม่พร้อม กรุณาโหลดใหม่';return false;}const b=form.querySelector('[type=submit]')||form.querySelector('button.primary');if(b.disabled)return false;b.disabled=true;try{const {error}=await rpc(action,args);if(error)throw error;$(target).textContent='';historyLoaded=false;await load(true);notice(success);return true;}catch(e){$(target).textContent='บันทึกไม่สำเร็จ: '+e.message;return false;}finally{b.disabled=false;}}
 for(const id of ['plan-date','plan-scope','plan-person'])$('#'+id).addEventListener('change',renderPlan);
 for(const id of ['case-search','case-type','case-status'])$('#'+id).addEventListener(id==='case-search'?'input':'change',renderCases);
 for(const id of ['analytics-from','analytics-to','analytics-person','analytics-job','analytics-group'])$('#'+id).addEventListener('change',renderAnalytics);
 for(const id of ['audit-search','audit-from','audit-to'])$('#'+id).addEventListener(id==='audit-search'?'input':'change',()=>{auditLimit=50;renderAudit();});
 $('#audit-reload').addEventListener('click',fetchHistory);$('#audit-more').addEventListener('click',()=>{auditLimit+=50;renderAudit();});
 $('#system-reset').addEventListener('click',async()=>{await refresh();delete $('#system-form').dataset.dirty;renderSystem(true);});
 $('#system-standards').addEventListener('click',()=>showView('settings'));
 document.addEventListener('click',e=>{
  const ticketButton=e.target.closest('[data-management-ticket]');if(ticketButton){const t=state.tickets.find(t=>t.id===ticketButton.dataset.managementTicket);ctx.openTicket(t);return;}
  const pb=e.target.closest('[data-plan-id]');if(pb&&supervisor()){planTicket=structuredClone(state.tickets.find(t=>t.id===pb.dataset.planId));const f=$('#plan-form');$('#plan-title').textContent=planTicket.ticket_no;fillPeople(f.elements.assignee_id);for(const k of ['planned_date','priority','assignee_id'])f.elements[k].value=planTicket[k]||'';f.elements.due_at.value=toBangkokInput(planTicket.due_at);$('#plan-message').textContent='';$('#plan-dialog').showModal();}
  const cb=e.target.closest('[data-case-id]');if(cb&&canCases()){caseRow=varianceRows(state.tickets,state.management.cases).find(r=>r.ticket.id===cb.dataset.caseId&&r.index===Number(cb.dataset.caseIndex));const f=$('#case-form');$('#case-title').textContent=caseRow.ticket.ticket_no+' · '+caseRow.line.pk_code+' · '+(caseRow.delta<0?'ขาด ':'เกิน ')+number(Math.abs(caseRow.delta))+' '+caseRow.line.unit;f.elements.status.value=caseRow.status;f.elements.note.value=caseRow.case?.note||'';$('#case-message').textContent='';$('#case-dialog').showModal();}
  if(e.target.closest('#nav [data-view=audit]')){if(canCases())fetchHistory();else showView('dashboard');}
 });
 $('#plan-form').addEventListener('submit',async e=>{e.preventDefault();if(!supervisor()||!planTicket)return;const f=e.target,a={ticket_id:planTicket.id,planned_date:f.elements.planned_date.value,due_at:f.elements.due_at.value?fromBangkokInput(f.elements.due_at.value):'',assignee_id:f.elements.assignee_id.value,priority:f.elements.priority.value,expected:[planTicket.planned_date,planTicket.due_at,planTicket.priority,planTicket.assignee_id]};if(await save(f,'plan',a,'#plan-message','บันทึกแผนงานแล้ว'))$('#plan-dialog').close();});
 $('#case-form').addEventListener('submit',async e=>{e.preventDefault();if(!canCases()||!caseRow)return;const f=e.target;if(await save(f,'case',{ticket_id:caseRow.ticket.id,line_index:caseRow.index,fingerprint:caseRow.fingerprint,expected_updated_at:caseRow.case?.updated_at||'',status:f.elements.status.value,note:f.elements.note.value.trim()},'#case-message','บันทึกผลติดตามแล้ว'))$('#case-dialog').close();});
 $('#system-form').addEventListener('input',e=>e.currentTarget.dataset.dirty='true');
 $('#system-form').addEventListener('submit',async e=>{e.preventDefault();if(!supervisor())return;const f=e.target,s={...state.management.settings};for(const k of ['start','end','lunchStart','lunchEnd','exceptionOwnerId'])s[k]=f.elements[k].value;s.reasonNames=Object.fromEntries([...f.querySelectorAll('[data-reason-name]')].map(el=>[el.dataset.reasonName,el.value.trim()]));s.holidays=[...new Set(f.elements.holidays.value.split(/[\s,]+/).filter(Boolean))];const error=settingsError(s);if(error){$('#system-message').textContent=error;return;}if(await save(f,'settings',{settings:s,expected:settingsSnapshot},'#system-message','บันทึกตั้งค่าแล้ว')){delete f.dataset.dirty;renderSystem(true);}});
 $('#clerk-account-form').addEventListener('submit',async e=>{e.preventDefault();if(!supervisor())return;const f=e.target;if(await save(f,'clerk_account',{username:f.elements.username.value.trim(),password:f.elements.password.value},'#clerk-account-message','บันทึกบัญชีธุรการแล้ว'))f.reset();});
 $('#analytics-csv').addEventListener('click',()=>{const blob=new Blob([safeCsv([reportHeaders,...analyticsRows()])],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='PK-performance-'+today()+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 $('#analytics-print').addEventListener('click',()=>{renderAnalytics();$('#print-report').innerHTML=`<h1>รายงานผลการทำงาน PK WAREHOUSE</h1><p>${esc($('#analytics-summary').textContent)} · จาก ${esc($('#analytics-from').value||'ทั้งหมด')} ถึง ${esc($('#analytics-to').value||'ทั้งหมด')}</p>${$('#analytics-table').innerHTML}<p>เวลาสุทธิหักพัก นอกกะ และวันหยุดที่กำหนด · จำนวนรายการเป็นบรรทัดวัสดุ · ข้อมูลไม่ครบไม่ใช้เทียบความเร็ว</p>`;document.body.classList.add('print-tickets');window.print();});
 return {refresh,render,clear(){history=[];historyLoaded=false;$('#audit-list').innerHTML='';delete $('#system-form').dataset.dirty;}};
}
